language: php

php:
  - 7.1

env:
  - OXID_VERSION="dev-b-6.1-ce"

before_script:
  - ls -l
  - mkdir -p build/logs
  - composer selfupdate
  - composer install
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `oxid`;'
  - composer create-project --keep-vcs oxid-esales/oxideshop-project oxidesale ${OXID_VERSION}
  - echo "include __DIR__ . '/../../.travis/oxid_config.inc.php';" >> oxidesale/source/config.inc.php
  - oxidesale/vendor/bin/reset-shop
  - cd oxidesale/source

script:
  - ls -l
  - ../../vendor/bin/phpunit ../../tests/ --debug --stop-on-error --stop-on-failure

#
#after_success:
# - if [[ $TRAVIS_TAG != '' ]]; then php -d phar.readonly=0 build-phar -v"${TRAVIS_TAG}"; fi
# - travis_retry php vendor/bin/coveralls -v
#
#deploy:
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file: oxrun.phar
#  skip_cleanup: true
#  on:
#    tags: true
