language: php

php:
  - 7.1

services:
  - mysql

env:
  - OXID_VERSION="dev-b-6.2-ce"

cache:
  directories:
  - $HOME/.composer/cache

before_script:
  - mkdir -p build/logs
  - composer self-update --1
  - composer install
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `oxid`;'
  - composer create-project --keep-vcs oxid-esales/oxideshop-project oxid-esale ${OXID_VERSION}
  - echo "include __DIR__ . '/../../.travis/oxid_config.inc.php';" >> oxid-esale/source/config.inc.php
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `oxid`;'
  - mysql oxid < oxid-esale/source/Setup/Sql/database_schema.sql
  - mysql oxid < oxid-esale/vendor/oxid-esales/oxideshop-demodata-ce/src/demodata.sql
  - rm -rf oxid-esale/source/Setup
  - oxid-esale/vendor/bin/oe-eshop-db_views_generate
  - rm -rf oxid-esale/source/tmp/*
  - cd oxid-esale/source

script:
  - ../../vendor/bin/phpunit -c ../../phpunit.xml --debug --stop-on-error --stop-on-failure

after_success:
 - cd ../../
 - .travis/updateReadmeDoc.sh && .travis/git_push.sh
 - if [[ $TRAVIS_TAG != '' ]]; then php -d phar.readonly=0 build-phar -v"${TRAVIS_TAG}"; fi
 - travis_retry php vendor/bin/php-coveralls -v

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: oxrun.phar
  skip_cleanup: true
  on:
    tags: true
