services:
  Oxrun\Command\Cache\ClearCommand:
    tags:
      - { name: console.command, command: 'cache:clear' }
  Oxrun\Command\Config\GetCommand:
    tags:
      - { name: console.command, command: 'config:get' }
  Oxrun\Command\Config\SetCommand:
    tags:
      - { name: console.command, command: 'config:set' }
  Oxrun\Command\Config\ShopGetCommand:
    tags:
      - { name: console.command, command: 'config:shop:get' }
  Oxrun\Command\Config\ShopSetCommand:
    tags:
      - { name: console.command, command: 'config:shop:set' }
  Oxrun\Command\Database\AnonymizeCommand:
    tags:
      - { name: console.command, command: 'db:anonymize' }
  Oxrun\Command\Database\DumpCommand:
    tags:
      - { name: console.command, command: 'db:dump' }
  Oxrun\Command\Database\ImportCommand:
    tags:
      - { name: console.command, command: 'db:import' }
  Oxrun\Command\Database\Info:
    tags:
      - { name: console.command, command: 'db:info' }
  Oxrun\Command\Database\ListCommand:
    tags:
      - { name: console.command, command: 'db:list' }
  Oxrun\Command\Database\QueryCommand:
    tags:
      - { name: console.command, command: 'db:query' }
  Oxrun\Command\Misc\GenerateDocumentationCommand:
    tags:
      - { name: console.command, command: 'misc:generate:documentation' }
  Oxrun\Command\Misc\PhpstormMetadataCommand:
    tags:
      - { name: console.command, command: 'misc:phpstorm:metadata' }
  Oxrun\Command\Misc\RegisterCommand:
    tags:
      - { name: console.command, command: 'misc:register:command' }
  Oxrun\Command\Module\GenerateCommand:
    tags:
      - { name: console.command, command: 'module:generate' }
  Oxrun\Command\Module\ListCommand:
    tags:
      - { name: console.command, command: 'module:list' }
  Oxrun\Command\Module\ReloadCommand:
    tags:
      - { name: console.command, command: 'module:reload' }
  Oxrun\Command\Oxid\ShopListCommand:
    tags:
      - { name: console.command, command: 'oxid:shops' }
  Oxrun\Command\Route\DebugCommand:
    tags:
      - { name: console.command, command: 'route:debug' }
  Oxrun\Command\User\CreateUserCommand:
    tags:
      - { name: console.command, command: 'user:create' }
  Oxrun\Command\User\PasswordCommand:
    tags:
      - { name: console.command, command: 'user:password' }
  Oxrun\Command\Views\UpdateCommand:
    tags:
      - { name: console.command, command: 'views:update' }
  Oxrun\Command\Config\UpdateYaml:
    tags:
      - { name: console.command }
    autowire: true
  Oxrun\Command\Config\MultiSetCommand:
    tags:
      - { name: console.command }
    autowire: true
  Oxrun\Command\Misc\GenerateYamlConfigCommand:
    tags:
      - { name: console.command }
    autowire: true
  Oxrun\Command\Module\MultiActivatorCommand:
    tags:
      - { name: console.command }
    autowire: true
  Oxrun\Command\Misc\GenerateYamlModuleListCommand:
    tags:
      - { name: console.command }
    autowire: true
  Oxrun\Command\Config\LinkEnvironment:
    tags:
      - { name: console.command }
    autowire: true
