name: oxrun tests

on: [push]

jobs:
#  stand_alone_checks:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Validate composer.json
#        run: composer validate
#      - name: validate php syntax
#        run: find . -not -path "./vendor/*" -name "*.php" -print0 | xargs -0 -n1 -P8 php -l

  tests:
#    needs: stand_alone_checks
    strategy:
      matrix:
        php: ["8.0"] # [7.3, 7.4, 8.0]
        oxid: ["6.3"] # [6.2, 6.3]
    runs-on: ubuntu-latest
    container:
      image: oxidesales/oxideshop-docker-php:${{matrix.php}}
      env:
        COMPILATION_VERSION: dev-b-${{matrix.oxid}}-ce
        DOCKER_DOCUMENT_ROOT: /var/www/oxid-esale
        MYSQL_HOST: oxid_db
        MYSQL_DATABASE: 'oxid'
        MYSQL_USER: "oxid"
        MYSQL_PASSWORD: "oxid"
        OXID_SHOP_URL: "http://localhost"
    services:
      oxid_db:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: oxid
          MYSQL_USER: oxid
          MYSQL_PASSWORD: oxid
          MYSQL_ROOT_PASSWORD: oxid
          TZ: Europe/Berlin
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
      - name: paramertees
        run: set
      - name: setup oxid
        run: bash ./docker/bin/installOxid.sh
#      - name: try to install phpstan-phpunit
#        run: composer require --working-dir=/var/www/oxideshop --dev phpstan/phpstan-phpunit
#        continue-on-error: true
#      - name: phpstan
#        continue-on-error: true
#        run: |
#          MD=$(pwd)
#          cd /var/www/oxideshop/
#          vendor/bin/phpstan analys --configuration phpstan.neon $MD
#      - name: phpstan loose
#        continue-on-error: true
#        run: |
#          MD=$(pwd)
#          cd /var/www/oxideshop/
#          composer remove phpstan/phpstan-strict-rules --dev
#          composer remove phpstan/phpstan-deprecation-rules --dev
#          vendor/bin/phpstan analys  --level 2 --configuration phpstan.neon $MD
#      - name: psalm
#        run: |
#          MD=$(pwd)
#          cd /var/www/oxideshop/
#          cat autoload.oxid.php
#          curl -OL https://circleci.com/api/v1.1/project/github/weirdan/psalm/232/artifacts/0/home/docker/project/build/psalm.phar
#          php psalm.phar --stats --debug-by-line --show-info=true $MD
#      - name: run tests
#        run: |
#          cd /var/www/oxideshop/
#          vendor/bin/runtests
#          ls -al source/log
#      - name: run oxid console list
#        run: |
#          cd /var/www/oxideshop
#          vendor/bin/oxid
#      - name: run in oxid console for all shops
#        run: |
#          cd /var/www/oxideshop
#          vendor/bin/oxid -vvv fix:states -a
#      - name: oxrun list
#        continue-on-error: ${{matrix.oxid != 6.1}}
#        run: |
#          cd /var/www/oxideshop
#          php oxrun.phar list
#      - name: oxrun fix
#        continue-on-error: ${{matrix.oxid != 6.1}}
#        run: |
#          cd /var/www/oxideshop
#          php oxrun.phar -vvv fix:states -a
#      - name: oxid console list
#        if: matrix.oxid != 6.1
#        run: |
#          cd /var/www/oxideshop
#          vendor/bin/oe-console list
#      - name: oxid console fix
#        if: matrix.oxid != 6.1
#        run: |
#          cd /var/www/oxideshop
#          vendor/bin/oe-console -vvv fix:states -a
#
